### ISSUE TITLE
"no such prop content_margin"

### ISSUE THREAD

**Issue by AWTrost** [amisarca/sublime-text-theme-night#2]
When using this theme in windows 7 (32 and 64 bit) when the mouse pointer is moved over the sidebar the sublime console logs `no such prop content_margin` over and over again.  It doesn't seem to actually cause a problem, as I'm still able to use the theme, but it fills my console up and makes it hard to find anything.

EDIT: also happens in OS X Lion

**Comment by WMeldon** [comment]
Removing line 335 ("content_margin": [1,1,10,10]" in class "sidebar_label") fixed this for me.
